/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javafx.scene.paint.Color;

/**
 *
 * @author tomjo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
        Rechercher.setForeground(new java.awt.Color(0, 0, 0));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        recherchePanel.setVisible(true);
        ajoutPanel.setVisible(false);
        supprimerPanel.setVisible(false);
        modifierPanel.setVisible(false);
        deconnexionPanel.setVisible(false);
        eleve.setForeground(new java.awt.Color(0, 0, 0));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'élève recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        Ajouter = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Deconnexion = new javax.swing.JButton();
        Rechercher = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        annee = new javax.swing.JButton();
        eleve = new javax.swing.JButton();
        enseignant = new javax.swing.JButton();
        inscription = new javax.swing.JButton();
        classe = new javax.swing.JButton();
        niveau = new javax.swing.JButton();
        bulletin = new javax.swing.JButton();
        enseignement = new javax.swing.JButton();
        discipline = new javax.swing.JButton();
        bulletindetail = new javax.swing.JButton();
        evaluation = new javax.swing.JButton();
        trimestre = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        recherchePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bddListe = new javax.swing.JList<>();
        resultatLabel = new javax.swing.JLabel();
        rechercheLabel = new javax.swing.JLabel();
        rechercheField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ajoutPanel = new javax.swing.JPanel();
        ajouterButton = new javax.swing.JButton();
        erreurLabel = new javax.swing.JLabel();
        ajout5Label = new javax.swing.JLabel();
        ajout1Label = new javax.swing.JLabel();
        ajout2Label = new javax.swing.JLabel();
        ajout3Label = new javax.swing.JLabel();
        ajout4Label = new javax.swing.JLabel();
        ajout3Field = new javax.swing.JTextField();
        ajout1Field = new javax.swing.JTextField();
        ajout2Field = new javax.swing.JTextField();
        ajout5Field = new javax.swing.JTextField();
        ajout4Field = new javax.swing.JTextField();
        supprimerPanel = new javax.swing.JPanel();
        supprimerButton = new javax.swing.JButton();
        supprimerLabel = new javax.swing.JLabel();
        supprimerField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supprimerList = new javax.swing.JList<>();
        supprimerResultLabel = new javax.swing.JLabel();
        modifierPanel = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        rechercheModifierPanel = new javax.swing.JPanel();
        rechercheModifierLabel = new javax.swing.JLabel();
        rechercheModifierField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        rechercheModifierList = new javax.swing.JList<>();
        rechercheModifierButton = new javax.swing.JButton();
        rechercheResultatModifierLabel = new javax.swing.JLabel();
        modifierModifierPanel = new javax.swing.JPanel();
        modifier1Button = new javax.swing.JLabel();
        modifier2Button = new javax.swing.JLabel();
        modifier3Button = new javax.swing.JLabel();
        modifier4Button = new javax.swing.JLabel();
        modifier5Button = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        valeur5Field = new javax.swing.JTextField();
        valeur1Field = new javax.swing.JTextField();
        valeur2Field = new javax.swing.JTextField();
        valeur3Field = new javax.swing.JTextField();
        valeur4Field = new javax.swing.JTextField();
        modifierValiderButton = new javax.swing.JButton();
        deconnexionPanel = new javax.swing.JPanel();

        jMenu9.setText("Eleve");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Professeur");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setText("Ajouter");
        Ajouter.setContentAreaFilled(false);
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setText("Supprimer");
        Supprimer.setContentAreaFilled(false);
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setText("Modifier");
        Modifier.setContentAreaFilled(false);
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Deconnexion.setBackground(new java.awt.Color(102, 102, 255));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setText("Déconnexion");
        Deconnexion.setContentAreaFilled(false);
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });

        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Rechercher.setText("Rechercher");
        Rechercher.setContentAreaFilled(false);
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Rechercher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ajouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Supprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deconnexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter)
                    .addComponent(Supprimer)
                    .addComponent(Modifier)
                    .addComponent(Rechercher)
                    .addComponent(Deconnexion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 181, 255));

        annee.setForeground(new java.awt.Color(255, 255, 255));
        annee.setText("Année scolaire");
        annee.setContentAreaFilled(false);
        annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeActionPerformed(evt);
            }
        });

        eleve.setForeground(new java.awt.Color(255, 255, 255));
        eleve.setText("Eleve");
        eleve.setContentAreaFilled(false);
        eleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eleveActionPerformed(evt);
            }
        });

        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setText("Enseignant");
        enseignant.setContentAreaFilled(false);
        enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enseignantActionPerformed(evt);
            }
        });

        inscription.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setText("Inscription");
        inscription.setContentAreaFilled(false);
        inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionActionPerformed(evt);
            }
        });

        classe.setForeground(new java.awt.Color(255, 255, 255));
        classe.setText("Classe");
        classe.setContentAreaFilled(false);
        classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classeActionPerformed(evt);
            }
        });

        niveau.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setText("Niveau");
        niveau.setContentAreaFilled(false);
        niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niveauActionPerformed(evt);
            }
        });

        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setText("Bulletin");
        bulletin.setContentAreaFilled(false);
        bulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulletinActionPerformed(evt);
            }
        });

        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setText("Enseignement");
        enseignement.setContentAreaFilled(false);
        enseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enseignementActionPerformed(evt);
            }
        });

        discipline.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setText("Discipline");
        discipline.setContentAreaFilled(false);
        discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplineActionPerformed(evt);
            }
        });

        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setText("Bulletin détaillé");
        bulletindetail.setContentAreaFilled(false);
        bulletindetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulletindetailActionPerformed(evt);
            }
        });

        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setText("Evaluation");
        evaluation.setContentAreaFilled(false);
        evaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationActionPerformed(evt);
            }
        });

        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setText("Trimestre");
        trimestre.setContentAreaFilled(false);
        trimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trimestreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(eleve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enseignant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inscription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(niveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trimestre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bulletin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enseignement))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(discipline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulletindetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(evaluation)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eleve)
                    .addComponent(enseignant)
                    .addComponent(inscription)
                    .addComponent(classe)
                    .addComponent(niveau)
                    .addComponent(annee)
                    .addComponent(trimestre)
                    .addComponent(bulletin)
                    .addComponent(enseignement))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discipline)
                    .addComponent(bulletindetail)
                    .addComponent(evaluation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bddListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(bddListe);

        resultatLabel.setText("Résultats :");

        rechercheLabel.setText("Identifiant :");

        jButton1.setText("Rechercher");

        javax.swing.GroupLayout recherchePanelLayout = new javax.swing.GroupLayout(recherchePanel);
        recherchePanel.setLayout(recherchePanelLayout);
        recherchePanelLayout.setHorizontalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(resultatLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE))
                    .addGroup(recherchePanelLayout.createSequentialGroup()
                        .addComponent(rechercheLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rechercheField, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recherchePanelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, Short.MAX_VALUE))
        );
        recherchePanelLayout.setVerticalGroup(
            recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recherchePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(recherchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rechercheLabel)
                    .addComponent(rechercheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(resultatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        ajouterButton.setText("Ajouter");

        erreurLabel.setText("ERREUR");

        ajout5Label.setText("ajout5 :");

        ajout1Label.setText("ajout1 :");

        ajout2Label.setText("ajout2 :");

        ajout3Label.setText("ajout3 :");

        ajout4Label.setText("ajout4 :");

        ajout1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout1FieldActionPerformed(evt);
            }
        });

        ajout4Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout4FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoutPanelLayout = new javax.swing.GroupLayout(ajoutPanel);
        ajoutPanel.setLayout(ajoutPanelLayout);
        ajoutPanelLayout.setHorizontalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPanelLayout.createSequentialGroup()
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erreurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ajoutPanelLayout.createSequentialGroup()
                                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                                        .addComponent(ajout1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ajout1Field))
                                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                                        .addComponent(ajout2Label)
                                        .addGap(42, 42, 42)
                                        .addComponent(ajout2Field))
                                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                                        .addComponent(ajout3Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ajout3Field))
                                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                                        .addComponent(ajout5Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ajout5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                                        .addComponent(ajout4Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ajout4Field)))
                                .addGap(0, 12, Short.MAX_VALUE))))
                    .addGroup(ajoutPanelLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(ajouterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ajoutPanelLayout.setVerticalGroup(
            ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajout1Label)
                    .addComponent(ajout1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajout2Label)
                    .addComponent(ajout2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajout3Label)
                    .addComponent(ajout3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajout4Label)
                    .addComponent(ajout4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ajoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajout5Label)
                    .addComponent(ajout5Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajouterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(erreurLabel)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        supprimerButton.setText("Supprimer");

        supprimerLabel.setText("Identifiant :");

        supprimerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(supprimerList);

        supprimerResultLabel.setText("ERREUR");

        javax.swing.GroupLayout supprimerPanelLayout = new javax.swing.GroupLayout(supprimerPanel);
        supprimerPanel.setLayout(supprimerPanelLayout);
        supprimerPanelLayout.setHorizontalGroup(
            supprimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supprimerPanelLayout.createSequentialGroup()
                .addGroup(supprimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supprimerPanelLayout.createSequentialGroup()
                        .addGroup(supprimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(supprimerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(supprimerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supprimerField))
                            .addGroup(supprimerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(supprimerResultLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(supprimerPanelLayout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(supprimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        supprimerPanelLayout.setVerticalGroup(
            supprimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supprimerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(supprimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimerLabel)
                    .addComponent(supprimerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supprimerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supprimerResultLabel)
                .addGap(23, 23, 23))
        );

        rechercheModifierLabel.setText("Identifiant :");

        rechercheModifierList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(rechercheModifierList);

        rechercheModifierButton.setText("Modifier");

        rechercheResultatModifierLabel.setText("ERREUR");

        javax.swing.GroupLayout rechercheModifierPanelLayout = new javax.swing.GroupLayout(rechercheModifierPanel);
        rechercheModifierPanel.setLayout(rechercheModifierPanelLayout);
        rechercheModifierPanelLayout.setHorizontalGroup(
            rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheModifierPanelLayout.createSequentialGroup()
                .addGroup(rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rechercheModifierPanelLayout.createSequentialGroup()
                        .addGap(703, 703, 703)
                        .addComponent(rechercheModifierButton))
                    .addGroup(rechercheModifierPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rechercheResultatModifierLabel)
                            .addGroup(rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addGroup(rechercheModifierPanelLayout.createSequentialGroup()
                                    .addComponent(rechercheModifierLabel)
                                    .addGap(96, 96, 96)
                                    .addComponent(rechercheModifierField, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        rechercheModifierPanelLayout.setVerticalGroup(
            rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheModifierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rechercheModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercheModifierLabel)
                    .addComponent(rechercheModifierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(rechercheModifierButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(rechercheResultatModifierLabel)
                .addGap(94, 94, 94))
        );

        modifier1Button.setText("modifier 1:");

        modifier2Button.setText("modifier 2 :");

        modifier3Button.setText("modifier 3 :");

        modifier4Button.setText("modifier 4:");

        modifier5Button.setText("modifier 5 :");

        jLabel6.setText("ERREUR");

        valeur5Field.setText("valeur5");

        valeur1Field.setText("valeur1");

        valeur2Field.setText("valeur2");

        valeur3Field.setText("valeur3");

        valeur4Field.setText("valeur4");

        modifierValiderButton.setText("Valider la modification");

        javax.swing.GroupLayout modifierModifierPanelLayout = new javax.swing.GroupLayout(modifierModifierPanel);
        modifierModifierPanel.setLayout(modifierModifierPanelLayout);
        modifierModifierPanelLayout.setHorizontalGroup(
            modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                            .addComponent(modifier1Button)
                            .addGap(41, 41, 41)
                            .addComponent(valeur1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE))
                        .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                            .addComponent(modifier2Button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valeur2Field))
                        .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                            .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modifier3Button)
                                .addComponent(modifier4Button)
                                .addComponent(modifier5Button, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(valeur4Field, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                                .addComponent(valeur3Field)
                                .addComponent(valeur5Field))))
                    .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(modifierValiderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        modifierModifierPanelLayout.setVerticalGroup(
            modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modifierModifierPanelLayout.createSequentialGroup()
                        .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier1Button)
                            .addComponent(valeur1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier2Button)
                            .addComponent(valeur2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier3Button)
                            .addComponent(valeur3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifier4Button)
                            .addComponent(valeur4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(modifierModifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modifier5Button)
                        .addComponent(valeur5Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(modifierValiderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayer(rechercheModifierPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(modifierModifierPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(rechercheModifierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 385, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(modifierModifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rechercheModifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(modifierModifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout modifierPanelLayout = new javax.swing.GroupLayout(modifierPanel);
        modifierPanel.setLayout(modifierPanelLayout);
        modifierPanelLayout.setHorizontalGroup(
            modifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        modifierPanelLayout.setVerticalGroup(
            modifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );

        javax.swing.GroupLayout deconnexionPanelLayout = new javax.swing.GroupLayout(deconnexionPanel);
        deconnexionPanel.setLayout(deconnexionPanelLayout);
        deconnexionPanelLayout.setHorizontalGroup(
            deconnexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1955, Short.MAX_VALUE)
        );
        deconnexionPanelLayout.setVerticalGroup(
            deconnexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(recherchePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ajoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(supprimerPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modifierPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(deconnexionPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2057, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(126, Short.MAX_VALUE)
                    .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(166, 166, 166)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ajoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(supprimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(modifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(deconnexionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 99, Short.MAX_VALUE)
                    .addComponent(recherchePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ajoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(supprimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(modifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(deconnexionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajout4FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout4FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajout4FieldActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        Rechercher.setForeground(new java.awt.Color(0, 0, 0));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        recherchePanel.setVisible(true);
        ajoutPanel.setVisible(false);
        supprimerPanel.setVisible(false);
        modifierPanel.setVisible(false);
        deconnexionPanel.setVisible(false);
        resultatLabel.setText("");
        erreurLabel.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_RechercherActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setForeground(new java.awt.Color(0, 0, 0));
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        recherchePanel.setVisible(false);
        ajoutPanel.setVisible(true);
        supprimerPanel.setVisible(false);
        modifierPanel.setVisible(false);
        deconnexionPanel.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_AjouterActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setForeground(new java.awt.Color(0, 0, 0));
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        recherchePanel.setVisible(false);
        ajoutPanel.setVisible(false);
        supprimerPanel.setVisible(true);
        modifierPanel.setVisible(false);
        deconnexionPanel.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setForeground(new java.awt.Color(0, 0, 0));
        Deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        recherchePanel.setVisible(false);
        ajoutPanel.setVisible(false);
        supprimerPanel.setVisible(false);
        modifierPanel.setVisible(true);
        modifierModifierPanel.setVisible(false);
        rechercheModifierPanel.setVisible(true);
        deconnexionPanel.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ModifierActionPerformed

    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        Rechercher.setForeground(new java.awt.Color(255, 255, 255));
        Ajouter.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer.setForeground(new java.awt.Color(255, 255, 255));
        Modifier.setForeground(new java.awt.Color(255, 255, 255));
        Deconnexion.setForeground(new java.awt.Color(0, 0, 0));
        recherchePanel.setVisible(false);
        ajoutPanel.setVisible(false);
        supprimerPanel.setVisible(false);
        modifierPanel.setVisible(false);
        deconnexionPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_DeconnexionActionPerformed

    private void eleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eleveActionPerformed
        eleve.setForeground(new java.awt.Color(0, 0, 0));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'élève recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_eleveActionPerformed

    private void enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enseignantActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(0, 0, 0));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'enseignant recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_enseignantActionPerformed

    private void inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(0, 0, 0));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'inscription recherchée : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_inscriptionActionPerformed

    private void classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(0, 0, 0));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de la classe recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_classeActionPerformed

    private void niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niveauActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(0, 0, 0));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé du niveau recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_niveauActionPerformed

    private void anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(0, 0, 0));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'année recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_anneeActionPerformed

    private void trimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trimestreActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(0, 0, 0));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé du trimestre recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_trimestreActionPerformed

    private void bulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulletinActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(0, 0, 0));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé du bulletin recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_bulletinActionPerformed

    private void enseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enseignementActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(0, 0, 0));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de l'enseignement recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_enseignementActionPerformed

    private void disciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplineActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(0, 0, 0));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé de la discipline recherchée : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_disciplineActionPerformed

    private void bulletindetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulletindetailActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(0, 0, 0));
        evaluation.setForeground(new java.awt.Color(255, 255, 255));
        rechercheLabel.setText("Clé du bulletin détaillé recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_bulletindetailActionPerformed

    private void evaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationActionPerformed
        eleve.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        classe.setForeground(new java.awt.Color(255, 255, 255));
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        annee.setForeground(new java.awt.Color(255, 255, 255));
        trimestre.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        enseignement.setForeground(new java.awt.Color(255, 255, 255));
        discipline.setForeground(new java.awt.Color(255, 255, 255));
        bulletindetail.setForeground(new java.awt.Color(255, 255, 255));
        evaluation.setForeground(new java.awt.Color(0, 0, 0));
        rechercheLabel.setText("Clé de l'évaluation recherché : ");
        resultatLabel.setText("");
        erreurLabel.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_evaluationActionPerformed

    private void ajout1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajout1FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JButton Deconnexion;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField ajout1Field;
    private javax.swing.JLabel ajout1Label;
    private javax.swing.JTextField ajout2Field;
    private javax.swing.JLabel ajout2Label;
    private javax.swing.JTextField ajout3Field;
    private javax.swing.JLabel ajout3Label;
    private javax.swing.JTextField ajout4Field;
    private javax.swing.JLabel ajout4Label;
    private javax.swing.JTextField ajout5Field;
    private javax.swing.JLabel ajout5Label;
    private javax.swing.JPanel ajoutPanel;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JButton annee;
    private javax.swing.JList<String> bddListe;
    private javax.swing.JButton bulletin;
    private javax.swing.JButton bulletindetail;
    private javax.swing.JButton classe;
    private javax.swing.JPanel deconnexionPanel;
    private javax.swing.JButton discipline;
    private javax.swing.JButton eleve;
    private javax.swing.JButton enseignant;
    private javax.swing.JButton enseignement;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JButton evaluation;
    private javax.swing.JButton inscription;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel modifier1Button;
    private javax.swing.JLabel modifier2Button;
    private javax.swing.JLabel modifier3Button;
    private javax.swing.JLabel modifier4Button;
    private javax.swing.JLabel modifier5Button;
    private javax.swing.JPanel modifierModifierPanel;
    private javax.swing.JPanel modifierPanel;
    private javax.swing.JButton modifierValiderButton;
    private javax.swing.JButton niveau;
    private javax.swing.JTextField rechercheField;
    private javax.swing.JLabel rechercheLabel;
    private javax.swing.JButton rechercheModifierButton;
    private javax.swing.JTextField rechercheModifierField;
    private javax.swing.JLabel rechercheModifierLabel;
    private javax.swing.JList<String> rechercheModifierList;
    private javax.swing.JPanel rechercheModifierPanel;
    private javax.swing.JPanel recherchePanel;
    private javax.swing.JLabel rechercheResultatModifierLabel;
    private javax.swing.JLabel resultatLabel;
    private javax.swing.JButton supprimerButton;
    private javax.swing.JTextField supprimerField;
    private javax.swing.JLabel supprimerLabel;
    private javax.swing.JList<String> supprimerList;
    private javax.swing.JPanel supprimerPanel;
    private javax.swing.JLabel supprimerResultLabel;
    private javax.swing.JButton trimestre;
    private javax.swing.JTextField valeur1Field;
    private javax.swing.JTextField valeur2Field;
    private javax.swing.JTextField valeur3Field;
    private javax.swing.JTextField valeur4Field;
    private javax.swing.JTextField valeur5Field;
    // End of variables declaration//GEN-END:variables
}
